### ISSUE TITLE
How are you able to use guile modules  and the guix home container command? 

### ISSUE THREAD

**Issue by MirkoHernandez** [Tass0sm/dotfiles#1]
I'm trying to create a similar guix home configuration, but so far I'm unable to  get the guile modules working with guix home (it works if I have all the services created inside a single  home-configuration.scm file).

- I tried setting  GUILE_LOAD_PATH to the root folder 
- also using (add-to-load-path) inside the home-configuration.scm file. 
- also copying the source files to the guile/site dir.

But I keep running into a "no code for module" error. How do you manage to use guile modules in your guix configuration?.

**Comment by Tass0sm** [comment]
This also gave me trouble when I set up the modules for the first time. The solution depends on where your modules are located. Guile searches for modules inside every directory that is part of the `%load-path` variable. To append a directory to this list, use the `-L` flag when calling guile or guix. For example, this is the load path of guix after giving it this argument.

```
$ guix repl -L /home/tassos/software/tassos-guix
scheme@(guix-user)> %load-path
$1 = ("/home/tassos/software/tassos-guix" "/gnu/store/7k6iiqj95x648plx1fw9qqr9ix1b1f2l-guix-module-union/share/guile/site/3.0" "/gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/share/guile/3.0" "/gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/share/guile/3.0" "/gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/share/guile/site/3.0" "/gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/share/guile/site" "/gnu/store/1jgcbdzx2ss6xv59w55g3kr3x4935dfb-guile-3.0.8/share/guile" "/home/tassos/.guix-profile/share/guile/site/3.0")
scheme@(guix-user)> ,use (tassos-guix packages emacs-xyz)
scheme@(guix-user)>
```

I've placed my guix home modules in `~/.config/guix/` right next to the symlink for the current guix profile. So just running `guix home -L ~/.config/guix reconfigure ~/.config/guix/home/environment.scm` won't work. If that `current` symlink is at the front of the load path, it will run into problems like this:

```
guix home: warning: failed to load '(current share guile site #{3.0}# gnu build linux-boot)':
no code for module (current share guile site #{3.0}# gnu build linux-boot)
/home/tassos/.config/guix/current/share/guile/site/3.0/gnu/build/linux-boot.scm:23:0: warning: module name (gnu build linux-boot) does not match file name 'current/share/guile/site/3.0/gnu/build/linux-boot.scm'
hint: File `/home/tassos/.config/guix/current/share/guile/site/3.0/gnu/build/linux-boot.scm' should probably
start with:

     (define-module (current share guile site #3.0

     # gnu build linux-boot))
```

Unfortunately, I don't completely understand the steps which cause that error. The solution is to *prepend* the directory to the load-path. The only method I know for doing that is by modifying the `GUILE_LOAD_PATH` variable. So here is my script for reconfiguration:

```bash
#!/usr/bin/env bash

cd /home/tassos/.config/guix/

# need to use this to prepend to the load path.
GUILE_LOAD_PATH=$GUILE_LOAD_PATH:${XDG_CONFIG_HOME:-$HOME/.config}/guix \
               guix home reconfigure -L "/home/tassos/software/tassos-guix" \
               home/environment.scm
```

I might put this script into the repo now.

Although, this is only necessary if there is that collision between your home environment modules and any other guix files. If they are located somewhere else, using `-L` should do the trick.

**Comment by MirkoHernandez** [comment]
Thank you.  I just found out about the -L option  and also guix repl (I was using the guile repl before) for debugging and I got it working. I was confused as to why the need of the -L option, my expectation was to just call guix home and the configuration file, I guess the -L should be required for most use cases.
